---
db:
  driver: dbi:Pg:harvester
  user: astro
  password: "***"
settings:
  size limit: 102400
  timeout: 90
  templates: templates
  output: html
jabber:
  jid: astrobot@spaceboyz.net/harvester
  password: UdtearOir6
  interval: 120
collections:
  ticker:
  - http://planet.c3bi.de/rss20.xml
  - http://www.blacksec.org/index2.php?option=com_rss&feed=RSS0.91&no_html=1
  - http://planet.entropia.de/rss.rdf
  - http://asocio.no-ip.com/unter-schwarzer-flagge/?feed=rss2
  projects:
  - "http://trac.c3d2.de/harvester/timeline?max=20&daysback=2&format=rss"
  links:
  - http://feeds.delicious.com/rss/fukami
  - http://feeds.delicious.com/rss/astro1138
  - http://feeds.delicious.com/rss/toidinamai
  - http://feeds.delicious.com/rss/r0b0
  - http://feeds.delicious.com/rss/pentabarf
  - http://feeds.delicious.com/rss/tigion
  - http://feeds.delicious.com/rss/turbo24prg
  - http://feeds.delicious.com/rss/mechko
  - http://feeds.delicious.com/rss/DerTobendeGummihammer
  - http://feeds.delicious.com/rss/Alien8
  - http://feeds.delicious.com/rss/boelthorn
  - http://feeds.delicious.com/rss/rabuju
  - http://feeds.delicious.com/rss/cosmoFlash
  - http://feeds.delicious.com/rss/Shnifti
  - http://feeds.delicious.com/rss/stepardo
  - http://feeds.delicious.com/rss/pq3x10
  - http://feeds.delicious.com/rss/the_roadrunner
  blogs:
  - http://www.c3d2.de/news-atom.xml
  - http://astroblog.spaceboyz.net/atom.rb
  - http://blog.tigion.de/feed/
  - http://blog.fukami.io/feed/atom/
  - http://blog.daemonized.de/feed/
  - http://www.psycast.de/blog/rss.php?ver=2
  - http://www.kuarepoti-dju.net/index.rss
  - http://89.238.64.223/semaphor/semaphor.php?item=blogRss
  - http://www.marvinnet.org/feed
  - http://d-ventures.heartofgold.de/?feed=rss2
  - http://jelena.blogsome.com/feed/rdf/
  - http://equiblog.diac24.net/$rss:full4
  - http://matthias.bsd-crew.de/blog/?feed=atom
  - http://blog.toidinamai.de/atom
  - http://berzerkely.net/atom/
  - http://bsd-crew.de/~riot/rss.xml
  - http://www.haltetdenbeat.de/feed/
  - http://leonweber.de/blog/feed/
  - http://klobs.kicks-ass.net/weblog/index.rss
  - http://kopfueber.wordpress.com/feed/
  - "http://www.jamendo.com/de/get/album/id/artist-license/page/rss2/336508/?ali=+info_min+images+info_min+info_common+info_common+images&ari=+info_min+info_min&lci=+info_min&o=release_date_desc"
  - "http://www.jamendo.com/en/get/album/id/artist-license/page/rss2/336634/?ali=+info_min+images+info_min+info_common+info_common+images&ari=+info_min+info_min&lci=+info_min&o=release_date_desc"
  - "http://www.jamendo.com/en/get/album/id/artist-license/page/rss2/336851/?ali=+info_min+images+info_min+info_common+info_common+images&ari=+info_min+info_min&lci=+info_min&o=release_date_desc"
  - http://www.gibpit.com/rss.xml
  - http://www.motobol.de/wordpress/?feed=atom
  - http://turbolent.com/atom
  - http://cthulhu.c3d2.de/~herr_flupke/randomnotes/bucket.xml
  - http://mapforce.blogspot.com/feeds/posts/default
  photos:
  - "http://api.flickr.com/services/feeds/photos_public.gne?id=73915810@N00&format=atom"
  - "http://api.flickr.com/services/feeds/photos_public.gne?id=58728439@N00&format=atom"
  - http://feed.fotolog.com/muff_divers/feed/main/rss20
  - "http://api.flickr.com/services/feeds/photos_public.gne?id=45064561@N00&format=atom"
  - "http://api.flickr.com/services/feeds/photos_public.gne?id=28511726@N00&format=atom"
  microblogs:
  - http://identi.ca/api/statuses/user_timeline/astro.atom
  - http://identi.ca/api/statuses/user_timeline/tigion.atom
  - http://identi.ca/api/statuses/user_timeline/daemonized.atom
  - http://identi.ca/api/statuses/user_timeline/blitz.atom


